import tkinter as tk
root = tk.Tk()
root.title("Buttons")
root.geometry("300x300")
label1 = tk.Label(root,text="Registration number")
label1.grid(row=0,column=0)
entry1 = tk.Entry(root)
entry1.grid(row=0,column=1)
label2 = tk.Label(root,text="Select your hobbies")
label2.grid(row=1,column=0)
cb1 = tk.Checkbutton(root,text="Learning")
cb1.grid(row=2,column=0)
cb2 = tk.Checkbutton(root,text="Singing")
cb2.grid(row=3,column=0)
cb3 = tk.Checkbutton(root,text="Dancing")
cb3.grid(row=4,column=0)
label3 = tk.Label(root,text="Section")
label3.grid(row=5,column=0)
rb1 = tk.Radiobutton(root,text="A",value=1)
rb1.grid(row=6,column=0)
rb2 = tk.Radiobutton(root,text="B",value=2)
rb2.grid(row=7,column=0)
rb3 = tk.Radiobutton(root,text="C",value=3)
rb3.grid(row=8,column=0)
root.mainloop()
